name: $(Build.Major).$(Build.Minor).$(BuildId)
trigger:
- master

variables:
  Build.Major: 1
  Build.Minor: 0
  Build.Patch: $(Build.BuildId)
  Build.Configuration: 'Release'
  Drops.Dir: $(Build.ArtifactStagingDirectory)/drops
  IQSharp.Hosting.Env: 'build-agent-katas'

jobs:
  - job: binaries
    displayName: 'Build Binary Packages'
    steps:
    - template: scripts/steps-init.yml
    - template: scripts/steps-binaries.yml

  - job: validate_projects
    displayName: 'Validate C# Projects'
    strategy:
      parallel:
        linux:
          imageName: 'ubuntu-latest'
        mac:
          imageName: 'macOS-latest'
        windows:
          imageName: 'windows-latest'
    pool: 
      vmImage: $(imageName)
    steps:
    - template: scripts/steps-init.yml

    - powershell: ./validate-unicode.ps1
      displayName: "Validating unicode characters"
      workingDirectory: $(System.DefaultWorkingDirectory)/scripts

    - powershell: ./validate-projects.ps1
      displayName: "Validating C# projects"
      workingDirectory: $(System.DefaultWorkingDirectory)/scripts

  - job: validate_notebooks
    displayName: 'Validate Notebooks'
    strategy:
      parallel:
        linux:
          imageName: 'ubuntu-latest'
        mac:
          imageName: 'macOS-latest'
        windows:
          imageName: 'windows-latest'
    pool: 
      vmImage: $(imageName)
    steps:
    - template: scripts/steps-init.yml

    - powershell: ./validate-notebooks.ps1
      displayName: "Validating notebooks"
      workingDirectory: $(System.DefaultWorkingDirectory)/scripts


